// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLl535qawSg7oPNAY4Fir3IRUID9UJS3A',
    appId: '1:819426796524:web:9bb456efbddd15843f96c9',
    messagingSenderId: '819426796524',
    projectId: 'sulam-nenaskita',
    authDomain: 'sulam-nenaskita.firebaseapp.com',
    storageBucket: 'sulam-nenaskita.firebasestorage.app',
    measurementId: 'G-5SE62VMLCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALA1PxuyBVjEGF29GBpnkms9dIUgYSMwk',
    appId: '1:819426796524:android:d6a44ed4a6b9d9e13f96c9',
    messagingSenderId: '819426796524',
    projectId: 'sulam-nenaskita',
    storageBucket: 'sulam-nenaskita.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4currTeSL0ypD5iuCiUOtStbetkD8Qww',
    appId: '1:819426796524:ios:de22c102a76fe0403f96c9',
    messagingSenderId: '819426796524',
    projectId: 'sulam-nenaskita',
    storageBucket: 'sulam-nenaskita.firebasestorage.app',
    iosBundleId: 'com.example.nenasKita',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLl535qawSg7oPNAY4Fir3IRUID9UJS3A',
    appId: '1:819426796524:web:fa018e492fc00e073f96c9',
    messagingSenderId: '819426796524',
    projectId: 'sulam-nenaskita',
    authDomain: 'sulam-nenaskita.firebaseapp.com',
    storageBucket: 'sulam-nenaskita.firebasestorage.app',
    measurementId: 'G-FD636BZMY0',
  );

}